version: '2'
services:
    broly-app:
        image: broly
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://broly-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=broly
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    broly-mongodb:
        extends:
            file: mongodb.yml
            service: broly-mongodb
